import {CountryNameModel} from '../models/logistics/countryName.model';

export let countryName: CountryNameModel[] = [
        {"Id":"1","Code":"AD","ThreeCode":"AND","NumberCode":"20","Name":"Andorra","ChineseName":"安道尔"},
        {"Id":"2","Code":"AE","ThreeCode":"ARE","NumberCode":"784","Name":"United Arab Emirates","ChineseName":"阿联酋"},
        {"Id":"3","Code":"AF","ThreeCode":"AFG","NumberCode":"4","Name":"Afghanistan","ChineseName":"阿富汗"},
        {"Id":"4","Code":"AG","ThreeCode":"ATG","NumberCode":"28","Name":"Antigua and Barbuda","ChineseName":"安提瓜和巴布达"},
        {"Id":"5","Code":"AI","ThreeCode":"AIA","NumberCode":"660","Name":"Anguilla","ChineseName":"安圭拉"},
        {"Id":"6","Code":"AL","ThreeCode":"ALB","NumberCode":"8","Name":"Albania","ChineseName":"阿尔巴尼亚"},
        {"Id":"7","Code":"AM","ThreeCode":"ARM","NumberCode":"51","Name":"Armenia","ChineseName":"亚美尼亚"},
        {"Id":"8","Code":"AO","ThreeCode":"AGO","NumberCode":"24","Name":"Angola","ChineseName":"安哥拉"},
        {"Id":"9","Code":"AQ","ThreeCode":"ATA","NumberCode":"10","Name":"Antarctica","ChineseName":"南极洲"},
        {"Id":"10","Code":"AR","ThreeCode":"ARG","NumberCode":"32","Name":"Argentina","ChineseName":"阿根廷"},
        {"Id":"11","Code":"AS","ThreeCode":"ASM","NumberCode":"16","Name":"American Samoa","ChineseName":"美属萨摩亚"},
        {"Id":"12","Code":"AT","ThreeCode":"AUT","NumberCode":"40","Name":"Austria","ChineseName":"奥地利"},
        {"Id":"13","Code":"AU","ThreeCode":"AUS","NumberCode":"36","Name":"Australia","ChineseName":"澳大利亚"},
        {"Id":"14","Code":"AW","ThreeCode":"ABW","NumberCode":"533","Name":"Aruba","ChineseName":"阿鲁巴"},
        {"Id":"15","Code":"AX","ThreeCode":"ALA","NumberCode":"248","Name":"?aland Islands","ChineseName":"奥兰群岛"},
        {"Id":"16","Code":"AZ","ThreeCode":"AZE","NumberCode":"31","Name":"Azerbaijan","ChineseName":"阿塞拜疆"},
        {"Id":"17","Code":"BA","ThreeCode":"BIH","NumberCode":"70","Name":"Bosnia and Herzegovina","ChineseName":"波黑"},
        {"Id":"18","Code":"BB","ThreeCode":"BRB","NumberCode":"52","Name":"Barbados","ChineseName":"巴巴多斯"},
        {"Id":"19","Code":"BD","ThreeCode":"BGD","NumberCode":"50","Name":"Bangladesh","ChineseName":"孟加拉"},
        {"Id":"20","Code":"BE","ThreeCode":"BEL","NumberCode":"56","Name":"Belgium","ChineseName":"比利时"},
        {"Id":"21","Code":"BF","ThreeCode":"BFA","NumberCode":"854","Name":"Burkina Faso","ChineseName":"布基纳法索"},
        {"Id":"22","Code":"BG","ThreeCode":"BGR","NumberCode":"100","Name":"Bulgaria","ChineseName":"保加利亚"},
        {"Id":"23","Code":"BH","ThreeCode":"BHR","NumberCode":"48","Name":"Bahrain","ChineseName":"巴林"},
        {"Id":"24","Code":"BI","ThreeCode":"BDI","NumberCode":"108","Name":"Burundi","ChineseName":"布隆迪"},
        {"Id":"25","Code":"BJ","ThreeCode":"BEN","NumberCode":"204","Name":"Benin","ChineseName":"贝宁"},
        {"Id":"26","Code":"BL","ThreeCode":"BLM","NumberCode":"652","Name":"Saint Barthélemy","ChineseName":"圣巴泰勒米岛"},
        {"Id":"27","Code":"BM","ThreeCode":"BMU","NumberCode":"60","Name":"Bermuda","ChineseName":"百慕大"},
        {"Id":"28","Code":"BN","ThreeCode":"BRN","NumberCode":"96","Name":"Brunei Darussalam","ChineseName":"文莱"},
        {"Id":"29","Code":"BO","ThreeCode":"BOL","NumberCode":"68","Name":"Bolivia, Plurinational","ChineseName":"玻利维亚"},
        {"Id":"30","Code":"BQ","ThreeCode":"BES","NumberCode":"535","Name":"Bonaire, Sint Eustatius and Saba","ChineseName":"荷兰加勒比区"},
        {"Id":"31","Code":"BR","ThreeCode":"BRA","NumberCode":"76","Name":"Brazil","ChineseName":"巴西"},
        {"Id":"32","Code":"BS","ThreeCode":"BHS","NumberCode":"44","Name":"Bahamas","ChineseName":"巴哈马"},
        {"Id":"33","Code":"BT","ThreeCode":"BTN","NumberCode":"64","Name":"Bhutan","ChineseName":"不丹"},
        {"Id":"34","Code":"BV","ThreeCode":"BVT","NumberCode":"74","Name":"Bouvet Island","ChineseName":"布韦岛"},
        {"Id":"35","Code":"BW","ThreeCode":"BWA","NumberCode":"72","Name":"Botswana","ChineseName":"博茨瓦纳"},
        {"Id":"36","Code":"BY","ThreeCode":"BLR","NumberCode":"112","Name":"Belarus","ChineseName":"白俄罗斯"},
        {"Id":"37","Code":"BZ","ThreeCode":"BLZ","NumberCode":"84","Name":"Belize","ChineseName":"伯利兹"},
        {"Id":"38","Code":"CA","ThreeCode":"CAN","NumberCode":"124","Name":"Canada","ChineseName":"加拿大"},
        {"Id":"39","Code":"CC","ThreeCode":"CCK","NumberCode":"166","Name":"Cocos (Keeling) Islands","ChineseName":"科科斯群岛"},
        {"Id":"40","Code":"CD","ThreeCode":"COD","NumberCode":"180","Name":"Congo, the Democratic Republic of the","ChineseName":"刚果（金）"},
        {"Id":"41","Code":"CF","ThreeCode":"CAF","NumberCode":"140","Name":"Central African Republic","ChineseName":"中非"},
        {"Id":"42","Code":"CG","ThreeCode":"COG","NumberCode":"178","Name":"Congo","ChineseName":"刚果（布）"},
        {"Id":"43","Code":"CH","ThreeCode":"CHE","NumberCode":"756","Name":"Switzerland","ChineseName":"瑞士"},
        {"Id":"44","Code":"CI","ThreeCode":"CIV","NumberCode":"384","Name":"Cote d Ivoire (Ivory Coast)","ChineseName":"科特迪瓦"},
        {"Id":"45","Code":"CK","ThreeCode":"COK","NumberCode":"184","Name":"Cook Islands","ChineseName":"库克群岛"},
        {"Id":"46","Code":"CL","ThreeCode":"CHL","NumberCode":"152","Name":"Chile","ChineseName":"智利"},
        {"Id":"47","Code":"CM","ThreeCode":"CMR","NumberCode":"120","Name":"Cameroon","ChineseName":"喀麦隆"},
        {"Id":"48","Code":"CN","ThreeCode":"CHN","NumberCode":"156","Name":"China","ChineseName":"中国"},
        {"Id":"49","Code":"CO","ThreeCode":"COL","NumberCode":"170","Name":"Colombia","ChineseName":"哥伦比亚"},
        {"Id":"50","Code":"CR","ThreeCode":"CRI","NumberCode":"188","Name":"Costa Rica","ChineseName":"哥斯达黎加"},
        {"Id":"51","Code":"CU","ThreeCode":"CUB","NumberCode":"192","Name":"Cuba","ChineseName":"古巴"},
        {"Id":"52","Code":"CV","ThreeCode":"CPV","NumberCode":"132","Name":"Cape Verde","ChineseName":"佛得角"},
        {"Id":"53","Code":"CW","ThreeCode":"CUW","NumberCode":"531","Name":"Cura?ao","ChineseName":"库拉索"},
        {"Id":"54","Code":"CX","ThreeCode":"CXR","NumberCode":"162","Name":"Christmas Island","ChineseName":"圣诞岛"},
        {"Id":"55","Code":"CY","ThreeCode":"CYP","NumberCode":"196","Name":"Cyprus","ChineseName":"塞浦路斯"},
        {"Id":"56","Code":"CZ","ThreeCode":"CZE","NumberCode":"203","Name":"Czech Republic","ChineseName":"捷克"},
        {"Id":"57","Code":"DE","ThreeCode":"DEU","NumberCode":"276","Name":"Germany","ChineseName":"德国"},
        {"Id":"58","Code":"DJ","ThreeCode":"DJI","NumberCode":"262","Name":"Djibouti","ChineseName":"吉布提"},
        {"Id":"59","Code":"DK","ThreeCode":"DNK","NumberCode":"208","Name":"Denmark","ChineseName":"丹麦"},
        {"Id":"60","Code":"DM","ThreeCode":"DMA","NumberCode":"212","Name":"Dominica","ChineseName":"多米尼克"},
        {"Id":"61","Code":"DO","ThreeCode":"DOM","NumberCode":"214","Name":"Dominican Republic","ChineseName":"多米尼加"},
        {"Id":"62","Code":"DZ","ThreeCode":"DZA","NumberCode":"12","Name":"Algeria","ChineseName":"阿尔及利亚"},
        {"Id":"63","Code":"EC","ThreeCode":"ECU","NumberCode":"218","Name":"Ecuador","ChineseName":"厄瓜多尔"},
        {"Id":"64","Code":"EE","ThreeCode":"EST","NumberCode":"233","Name":"Estonia","ChineseName":"爱沙尼亚"},
        {"Id":"65","Code":"EG","ThreeCode":"EGY","NumberCode":"818","Name":"Egypt","ChineseName":"埃及"},
        {"Id":"66","Code":"EH","ThreeCode":"ESH","NumberCode":"732","Name":"Western Sahara","ChineseName":"西撒哈拉"},
        {"Id":"67","Code":"ER","ThreeCode":"ERI","NumberCode":"232","Name":"Eritrea","ChineseName":"厄立特里亚"},
        {"Id":"68","Code":"ES","ThreeCode":"ESP","NumberCode":"724","Name":"Spain","ChineseName":"西班牙"},
        {"Id":"69","Code":"ET","ThreeCode":"ETH","NumberCode":"231","Name":"Ethiopia","ChineseName":"埃塞俄比亚"},
        {"Id":"70","Code":"FI","ThreeCode":"FIN","NumberCode":"246","Name":"Finland","ChineseName":"芬兰"},
        {"Id":"71","Code":"FJ","ThreeCode":"FJI","NumberCode":"242","Name":"Fiji","ChineseName":"斐济群岛"},
        {"Id":"72","Code":"FK","ThreeCode":"FLK","NumberCode":"238","Name":"Falkland Islands (Malvinas)","ChineseName":"马尔维纳斯群岛（福克兰）"},
        {"Id":"73","Code":"FM","ThreeCode":"FSM","NumberCode":"583","Name":"Micronesia, Federated States of","ChineseName":"密克罗尼西亚联邦"},
        {"Id":"74","Code":"FO","ThreeCode":"FRO","NumberCode":"234","Name":"Faroe Islands","ChineseName":"法罗群岛"},
        {"Id":"75","Code":"FR","ThreeCode":"FRA","NumberCode":"250","Name":"France","ChineseName":"法国"},
        {"Id":"76","Code":"GA","ThreeCode":"GAB","NumberCode":"266","Name":"Gabon","ChineseName":"加蓬"},
        {"Id":"77","Code":"GB","ThreeCode":"GBR","NumberCode":"826","Name":"United Kingdom","ChineseName":"英国"},
        {"Id":"78","Code":"GD","ThreeCode":"GRD","NumberCode":"308","Name":"Grenada","ChineseName":"格林纳达"},
        {"Id":"79","Code":"GE","ThreeCode":"GEO","NumberCode":"268","Name":"Georgia","ChineseName":"格鲁吉亚"},
        {"Id":"80","Code":"GF","ThreeCode":"GUF","NumberCode":"254","Name":"French Guiana","ChineseName":"法属圭亚那"},
        {"Id":"81","Code":"GG","ThreeCode":"GGY","NumberCode":"831","Name":"Guernsey","ChineseName":"根西岛"},
        {"Id":"82","Code":"GH","ThreeCode":"GHA","NumberCode":"288","Name":"Ghana","ChineseName":"加纳"},
        {"Id":"83","Code":"GI","ThreeCode":"GIB","NumberCode":"292","Name":"Gibraltar","ChineseName":"直布罗陀"},
        {"Id":"84","Code":"GL","ThreeCode":"GRL","NumberCode":"304","Name":"Greenland","ChineseName":"格陵兰岛"},
        {"Id":"85","Code":"GM","ThreeCode":"GMB","NumberCode":"270","Name":"Gambia","ChineseName":"冈比亚"},
        {"Id":"86","Code":"GN","ThreeCode":"GIN","NumberCode":"324","Name":"Guinea","ChineseName":"几内亚"},
        {"Id":"87","Code":"GP","ThreeCode":"GLP","NumberCode":"312","Name":"Guadeloupe","ChineseName":"瓜德罗普"},
        {"Id":"88","Code":"GQ","ThreeCode":"GNQ","NumberCode":"226","Name":"Equatorial Guinea","ChineseName":"赤道几内亚"},
        {"Id":"89","Code":"GR","ThreeCode":"GRC","NumberCode":"300","Name":"Greece","ChineseName":"希腊"},
        {"Id":"90","Code":"GS","ThreeCode":"SGS","NumberCode":"239","Name":"South Georgia and the South Sandwich Islands","ChineseName":"南乔治亚岛和南桑威奇群岛"},
        {"Id":"91","Code":"GT","ThreeCode":"GTM","NumberCode":"320","Name":"Guatemala","ChineseName":"危地马拉"},
        {"Id":"92","Code":"GU","ThreeCode":"GUM","NumberCode":"316","Name":"Guam","ChineseName":"关岛"},
        {"Id":"93","Code":"GW","ThreeCode":"GNB","NumberCode":"624","Name":"Guinea-Bissau","ChineseName":"几内亚比绍"},
        {"Id":"94","Code":"GY","ThreeCode":"GUY","NumberCode":"328","Name":"Guyana","ChineseName":"圭亚那"},
        {"Id":"95","Code":"HK","ThreeCode":"HKG","NumberCode":"344","Name":"Hong Kong","ChineseName":"香港"},
        {"Id":"96","Code":"HM","ThreeCode":"HMD","NumberCode":"334","Name":"Heard Island and McDonald Islands","ChineseName":"赫德岛和麦克唐纳群岛"},
        {"Id":"97","Code":"HN","ThreeCode":"HND","NumberCode":"340","Name":"Honduras","ChineseName":"洪都拉斯"},
        {"Id":"98","Code":"HR","ThreeCode":"HRV","NumberCode":"191","Name":"Croatia","ChineseName":"克罗地亚"},
        {"Id":"99","Code":"HT","ThreeCode":"HTI","NumberCode":"332","Name":"Haiti","ChineseName":"海地"},
        {"Id":"100","Code":"HU","ThreeCode":"HUN","NumberCode":"348","Name":"Hungary","ChineseName":"匈牙利"},
        {"Id":"101","Code":"ID","ThreeCode":"IDN","NumberCode":"360","Name":"Indonesia","ChineseName":"印度尼西亚"},
        {"Id":"102","Code":"IE","ThreeCode":"IRL","NumberCode":"372","Name":"Ireland","ChineseName":"爱尔兰"},
        {"Id":"103","Code":"IL","ThreeCode":"ISR","NumberCode":"376","Name":"Israel","ChineseName":"以色列"},
        {"Id":"104","Code":"IM","ThreeCode":"IMN","NumberCode":"833","Name":"Isle of Man","ChineseName":"马恩岛"},
        {"Id":"105","Code":"IN","ThreeCode":"IND","NumberCode":"356","Name":"India","ChineseName":"印度"},
        {"Id":"106","Code":"IO","ThreeCode":"IOT","NumberCode":"86","Name":"British Indian Ocean Territory","ChineseName":"英属印度洋领地"},
        {"Id":"107","Code":"IQ","ThreeCode":"IRQ","NumberCode":"368","Name":"Iraq","ChineseName":"伊拉克"},
        {"Id":"108","Code":"IR","ThreeCode":"IRN","NumberCode":"364","Name":"Iran, Islamic Republic of","ChineseName":"伊朗"},
        {"Id":"109","Code":"IS","ThreeCode":"ISL","NumberCode":"352","Name":"Iceland","ChineseName":"冰岛"},
        {"Id":"110","Code":"IT","ThreeCode":"ITA","NumberCode":"380","Name":"Italy","ChineseName":"意大利"},
        {"Id":"111","Code":"JE","ThreeCode":"JEY","NumberCode":"832","Name":"Jersey","ChineseName":"泽西岛"},
        {"Id":"112","Code":"JM","ThreeCode":"JAM","NumberCode":"388","Name":"Jamaica","ChineseName":"牙买加"},
        {"Id":"113","Code":"JO","ThreeCode":"JOR","NumberCode":"400","Name":"Jordan","ChineseName":"约旦"},
        {"Id":"114","Code":"JP","ThreeCode":"JPN","NumberCode":"392","Name":"Japan","ChineseName":"日本"},
        {"Id":"115","Code":"KE","ThreeCode":"KEN","NumberCode":"404","Name":"Kenya","ChineseName":"肯尼亚"},
        {"Id":"116","Code":"KG","ThreeCode":"KGZ","NumberCode":"417","Name":"Kyrgyzstan","ChineseName":"吉尔吉斯斯坦"},
        {"Id":"117","Code":"KH","ThreeCode":"KHM","NumberCode":"116","Name":"Cambodia","ChineseName":"柬埔寨"},
        {"Id":"118","Code":"KI","ThreeCode":"KIR","NumberCode":"296","Name":"Kiribati","ChineseName":"基里巴斯"},
        {"Id":"119","Code":"KM","ThreeCode":"COM","NumberCode":"174","Name":"Comoros","ChineseName":"科摩罗"},
        {"Id":"120","Code":"KN","ThreeCode":"KNA","NumberCode":"659","Name":"Saint Kitts and Nevis","ChineseName":"圣基茨和尼维斯"},
        {"Id":"121","Code":"KP","ThreeCode":"PRK","NumberCode":"408","Name":"Korea, Democratic People's Republic of","ChineseName":"朝鲜"},
        {"Id":"122","Code":"KR","ThreeCode":"KOR","NumberCode":"410","Name":"Korea, Republic of","ChineseName":"韩国"},
        {"Id":"123","Code":"KW","ThreeCode":"KWT","NumberCode":"414","Name":"Kuwait","ChineseName":"科威特"},
        {"Id":"124","Code":"KY","ThreeCode":"CYM","NumberCode":"136","Name":"Cayman Islands","ChineseName":"开曼群岛"},
        {"Id":"125","Code":"KZ","ThreeCode":"KAZ","NumberCode":"398","Name":"Kazakhstan","ChineseName":"哈萨克斯坦"},
        {"Id":"126","Code":"LA","ThreeCode":"LAO","NumberCode":"418","Name":"Lao People's Democratic Republic","ChineseName":"老挝"},
        {"Id":"127","Code":"LB","ThreeCode":"LBN","NumberCode":"422","Name":"Lebanon","ChineseName":"黎巴嫩"},
        {"Id":"128","Code":"LC","ThreeCode":"LCA","NumberCode":"662","Name":"Saint Lucia","ChineseName":"圣卢西亚"},
        {"Id":"129","Code":"LI","ThreeCode":"LIE","NumberCode":"438","Name":"Liechtenstein","ChineseName":"列支敦士登"},
        {"Id":"130","Code":"LK","ThreeCode":"LKA","NumberCode":"144","Name":"Sri Lanka","ChineseName":"斯里兰卡"},
        {"Id":"131","Code":"LR","ThreeCode":"LBR","NumberCode":"430","Name":"Liberia","ChineseName":"利比里亚"},
        {"Id":"132","Code":"LS","ThreeCode":"LSO","NumberCode":"426","Name":"Lesotho","ChineseName":"莱索托"},
        {"Id":"133","Code":"LT","ThreeCode":"LTU","NumberCode":"440","Name":"Lithuania","ChineseName":"立陶宛"},
        {"Id":"134","Code":"LU","ThreeCode":"LUX","NumberCode":"442","Name":"Luxembourg","ChineseName":"卢森堡"},
        {"Id":"135","Code":"LV","ThreeCode":"LVA","NumberCode":"428","Name":"Latvia","ChineseName":"拉脱维亚"},
        {"Id":"136","Code":"LY","ThreeCode":"LBY","NumberCode":"434","Name":"Libya","ChineseName":"利比亚"},
        {"Id":"137","Code":"MA","ThreeCode":"MAR","NumberCode":"504","Name":"Morocco","ChineseName":"摩洛哥"},
        {"Id":"138","Code":"MC","ThreeCode":"MCO","NumberCode":"492","Name":"Monaco","ChineseName":"摩纳哥"},
        {"Id":"139","Code":"MD","ThreeCode":"MDA","NumberCode":"498","Name":"Moldova, Republic of","ChineseName":"摩尔多瓦"},
        {"Id":"140","Code":"ME","ThreeCode":"MNE","NumberCode":"499","Name":"Montenegro","ChineseName":"黑山"},
        {"Id":"141","Code":"MF","ThreeCode":"MAF","NumberCode":"663","Name":"Saint Martin (French part)","ChineseName":"法属圣马丁"},
        {"Id":"142","Code":"MG","ThreeCode":"MDG","NumberCode":"450","Name":"Madagascar","ChineseName":"马达加斯加"},
        {"Id":"143","Code":"MH","ThreeCode":"MHL","NumberCode":"584","Name":"Marshall islands","ChineseName":"马绍尔群岛"},
        {"Id":"144","Code":"MK","ThreeCode":"MKD","NumberCode":"807","Name":"Macedonia, the former Yugoslav Republic of","ChineseName":"马其顿"},
        {"Id":"145","Code":"ML","ThreeCode":"MLI","NumberCode":"466","Name":"Mali","ChineseName":"马里"},
        {"Id":"146","Code":"MM","ThreeCode":"MMR","NumberCode":"104","Name":"Myanmar","ChineseName":"缅甸"},
        {"Id":"147","Code":"MN","ThreeCode":"MNG","NumberCode":"496","Name":"Mongolia","ChineseName":"蒙古"},
        {"Id":"148","Code":"MO","ThreeCode":"MAC","NumberCode":"446","Name":"Macao","ChineseName":"澳门"},
        {"Id":"149","Code":"MP","ThreeCode":"MNP","NumberCode":"580","Name":"Northern Mariana Islands","ChineseName":"北马里亚纳群岛"},
        {"Id":"150","Code":"MQ","ThreeCode":"MTQ","NumberCode":"474","Name":"Martinique","ChineseName":"马提尼克"},
        {"Id":"151","Code":"MR","ThreeCode":"MRT","NumberCode":"478","Name":"Mauritania","ChineseName":"毛里塔尼亚"},
        {"Id":"152","Code":"MS","ThreeCode":"MSR","NumberCode":"500","Name":"Montserrat","ChineseName":"蒙塞拉特岛"},
        {"Id":"153","Code":"MT","ThreeCode":"MLT","NumberCode":"470","Name":"Malta","ChineseName":"马耳他"},
        {"Id":"154","Code":"MU","ThreeCode":"MUS","NumberCode":"480","Name":"Mauritius","ChineseName":"毛里求斯"},
        {"Id":"155","Code":"MV","ThreeCode":"MDV","NumberCode":"462","Name":"Maldives","ChineseName":"马尔代夫"},
        {"Id":"156","Code":"MW","ThreeCode":"MWI","NumberCode":"454","Name":"Malawi","ChineseName":"马拉维"},
        {"Id":"157","Code":"MX","ThreeCode":"MEX","NumberCode":"484","Name":"Mexico","ChineseName":"墨西哥"},
        {"Id":"158","Code":"MY","ThreeCode":"MYS","NumberCode":"458","Name":"Malaysia","ChineseName":"马来西亚"},
        {"Id":"159","Code":"MZ","ThreeCode":"MOZ","NumberCode":"508","Name":"Mozambique","ChineseName":"莫桑比克"},
        {"Id":"160","Code":"NA","ThreeCode":"NAM","NumberCode":"516","Name":"Namibia","ChineseName":"纳米比亚"},
        {"Id":"161","Code":"NC","ThreeCode":"NCL","NumberCode":"540","Name":"New Caledonia","ChineseName":"新喀里多尼亚"},
        {"Id":"162","Code":"NE","ThreeCode":"NER","NumberCode":"562","Name":"Niger","ChineseName":"尼日尔"},
        {"Id":"163","Code":"NF","ThreeCode":"NFK","NumberCode":"574","Name":"Norfolk Island","ChineseName":"诺福克岛"},
        {"Id":"164","Code":"NG","ThreeCode":"NGA","NumberCode":"566","Name":"Nigeria","ChineseName":"尼日利亚"},
        {"Id":"165","Code":"NI","ThreeCode":"NIC","NumberCode":"558","Name":"Nicaragua","ChineseName":"尼加拉瓜"},
        {"Id":"166","Code":"NL","ThreeCode":"NLD","NumberCode":"528","Name":"Netherlands","ChineseName":"荷兰"},
        {"Id":"167","Code":"NO","ThreeCode":"NOR","NumberCode":"578","Name":"Norway","ChineseName":"挪威"},
        {"Id":"168","Code":"NP","ThreeCode":"NPL","NumberCode":"524","Name":"Nepal","ChineseName":"尼泊尔"},
        {"Id":"169","Code":"NR","ThreeCode":"NRU","NumberCode":"520","Name":"Nauru","ChineseName":"瑙鲁"},
        {"Id":"170","Code":"NU","ThreeCode":"NIU","NumberCode":"570","Name":"Niue","ChineseName":"纽埃"},
        {"Id":"171","Code":"NZ","ThreeCode":"NZL","NumberCode":"554","Name":"New Zealand","ChineseName":"新西兰"},
        {"Id":"172","Code":"OM","ThreeCode":"OMN","NumberCode":"512","Name":"Oman","ChineseName":"阿曼"},
        {"Id":"173","Code":"PA","ThreeCode":"PAN","NumberCode":"591","Name":"Panama","ChineseName":"巴拿马"},
        {"Id":"174","Code":"PE","ThreeCode":"PER","NumberCode":"604","Name":"Peru","ChineseName":"秘鲁"},
        {"Id":"175","Code":"PF","ThreeCode":"PYF","NumberCode":"258","Name":"French Polynesia","ChineseName":"法属波利尼西亚"},
        {"Id":"176","Code":"PG","ThreeCode":"PNG","NumberCode":"598","Name":"Papua New Guinea","ChineseName":"巴布亚新几内亚"},
        {"Id":"177","Code":"PH","ThreeCode":"PHL","NumberCode":"608","Name":"Philippines","ChineseName":"菲律宾"},
        {"Id":"178","Code":"PK","ThreeCode":"PAK","NumberCode":"586","Name":"Pakistan","ChineseName":"巴基斯坦"},
        {"Id":"179","Code":"PL","ThreeCode":"POL","NumberCode":"616","Name":"Poland","ChineseName":"波兰"},
        {"Id":"180","Code":"PM","ThreeCode":"SPM","NumberCode":"666","Name":"Saint Pierre and Miquelon","ChineseName":"圣皮埃尔和密克隆"},
        {"Id":"181","Code":"PN","ThreeCode":"PCN","NumberCode":"612","Name":"Pitcairn Islands","ChineseName":"皮特凯恩群岛"},
        {"Id":"182","Code":"PR","ThreeCode":"PRI","NumberCode":"630","Name":"Puerto Rico","ChineseName":"波多黎各"},
        {"Id":"183","Code":"PS","ThreeCode":"PSE","NumberCode":"275","Name":"Palestine, State of","ChineseName":"巴勒斯坦"},
        {"Id":"184","Code":"PT","ThreeCode":"PRT","NumberCode":"620","Name":"Portugal","ChineseName":"葡萄牙"},
        {"Id":"185","Code":"PW","ThreeCode":"PLW","NumberCode":"585","Name":"Palau","ChineseName":"帕劳"},
        {"Id":"186","Code":"PY","ThreeCode":"PRY","NumberCode":"600","Name":"Paraguay","ChineseName":"巴拉圭"},
        {"Id":"187","Code":"QA","ThreeCode":"QAT","NumberCode":"634","Name":"Qatar","ChineseName":"卡塔尔"},
        {"Id":"188","Code":"RE","ThreeCode":"REU","NumberCode":"638","Name":"Reunion Island Of","ChineseName":"留尼汪"},
        {"Id":"189","Code":"RO","ThreeCode":"ROU","NumberCode":"642","Name":"Romania","ChineseName":"罗马尼亚"},
        {"Id":"190","Code":"RS","ThreeCode":"SRB","NumberCode":"688","Name":"Serbia","ChineseName":"塞尔维亚"},
        {"Id":"191","Code":"RU","ThreeCode":"RUS","NumberCode":"643","Name":"Russian Federation","ChineseName":"俄罗斯"},
        {"Id":"192","Code":"RW","ThreeCode":"RWA","NumberCode":"646","Name":"Rwanda","ChineseName":"卢旺达"},
        {"Id":"193","Code":"SA","ThreeCode":"SAU","NumberCode":"682","Name":"Saudi Arabia","ChineseName":"沙特阿拉伯"},
        {"Id":"194","Code":"SB","ThreeCode":"SLB","NumberCode":"90","Name":"Solomon Islands","ChineseName":"所罗门群岛"},
        {"Id":"195","Code":"SC","ThreeCode":"SYC","NumberCode":"690","Name":"Seychelles","ChineseName":"塞舌尔"},
        {"Id":"196","Code":"SD","ThreeCode":"SDN","NumberCode":"729","Name":"Sudan","ChineseName":"苏丹"},
        {"Id":"197","Code":"SE","ThreeCode":"SWE","NumberCode":"752","Name":"Sweden","ChineseName":"瑞典"},
        {"Id":"198","Code":"SG","ThreeCode":"SGP","NumberCode":"702","Name":"Singapore","ChineseName":"新加坡"},
        {"Id":"199","Code":"SH","ThreeCode":"SHN","NumberCode":"654","Name":"Saint Helena, Ascension and Tristan da Cunha","ChineseName":"圣赫勒拿"},
        {"Id":"200","Code":"SI","ThreeCode":"SVN","NumberCode":"705","Name":"Slovenia","ChineseName":"斯洛文尼亚"},
        {"Id":"201","Code":"SJ","ThreeCode":"SJM","NumberCode":"744","Name":"Svalbard and Jan Mayen","ChineseName":"斯瓦尔巴群岛和扬马延岛"},
        {"Id":"202","Code":"SK","ThreeCode":"SVK","NumberCode":"703","Name":"Slovakia","ChineseName":"斯洛伐克"},
        {"Id":"203","Code":"SL","ThreeCode":"SLE","NumberCode":"694","Name":"Sierra Leone","ChineseName":"塞拉利昂"},
        {"Id":"204","Code":"SM","ThreeCode":"SMR","NumberCode":"674","Name":"San Marino","ChineseName":"圣马力诺"},
        {"Id":"205","Code":"SN","ThreeCode":"SEN","NumberCode":"686","Name":"Senegal","ChineseName":"塞内加尔"},
        {"Id":"206","Code":"SO","ThreeCode":"SOM","NumberCode":"706","Name":"Somalia","ChineseName":"索马里"},
        {"Id":"207","Code":"SR","ThreeCode":"SUR","NumberCode":"740","Name":"Suriname","ChineseName":"苏里南"},
        {"Id":"208","Code":"SS","ThreeCode":"SSD","NumberCode":"728","Name":"South Sudan","ChineseName":"南苏丹"},
        {"Id":"209","Code":"ST","ThreeCode":"STP","NumberCode":"678","Name":"Sao Tome and Principe","ChineseName":"圣多美和普林西比"},
        {"Id":"210","Code":"SV","ThreeCode":"SLV","NumberCode":"222","Name":"El Salvador","ChineseName":"萨尔瓦多"},
        {"Id":"211","Code":"SX","ThreeCode":"SXM","NumberCode":"534","Name":"Sint Maarten (Dutch part)","ChineseName":"荷属圣马丁"},
        {"Id":"212","Code":"SY","ThreeCode":"SYR","NumberCode":"760","Name":"Syrian Arab Republic","ChineseName":"叙利亚"},
        {"Id":"213","Code":"SZ","ThreeCode":"SWZ","NumberCode":"748","Name":"Swaziland","ChineseName":"斯威士兰"},
        {"Id":"214","Code":"TC","ThreeCode":"TCA","NumberCode":"796","Name":"Turks and Caicos Islands","ChineseName":"特克斯和凯科斯群岛"},
        {"Id":"215","Code":"TD","ThreeCode":"TCD","NumberCode":"148","Name":"Chad","ChineseName":"乍得"},
        {"Id":"216","Code":"TF","ThreeCode":"ATF","NumberCode":"260","Name":"French Southern Territories","ChineseName":"法属南部领地"},
        {"Id":"217","Code":"TG","ThreeCode":"TGO","NumberCode":"768","Name":"Togo","ChineseName":"多哥"},
        {"Id":"218","Code":"TH","ThreeCode":"THA","NumberCode":"764","Name":"Thailand","ChineseName":"泰国"},
        {"Id":"219","Code":"TJ","ThreeCode":"TJK","NumberCode":"762","Name":"Tajikistan","ChineseName":"塔吉克斯坦"},
        {"Id":"220","Code":"TK","ThreeCode":"TKL","NumberCode":"772","Name":"Tokelau","ChineseName":"托克劳"},
        {"Id":"221","Code":"TL","ThreeCode":"TLS","NumberCode":"626","Name":"Timor-Leste","ChineseName":"东帝汶"},
        {"Id":"222","Code":"TM","ThreeCode":"TKM","NumberCode":"795","Name":"Turkmenistan","ChineseName":"土库曼斯坦"},
        {"Id":"223","Code":"TN","ThreeCode":"TUN","NumberCode":"788","Name":"Tunisia","ChineseName":"突尼斯"},
        {"Id":"224","Code":"TO","ThreeCode":"TON","NumberCode":"776","Name":"Tonga","ChineseName":"汤加"},
        {"Id":"225","Code":"TR","ThreeCode":"TUR","NumberCode":"792","Name":"Turkey","ChineseName":"土耳其"},
        {"Id":"226","Code":"TT","ThreeCode":"TTO","NumberCode":"780","Name":"Trinidad and Tobago","ChineseName":"特立尼达和多巴哥"},
        {"Id":"227","Code":"TV","ThreeCode":"TUV","NumberCode":"798","Name":"Tuvalu","ChineseName":"图瓦卢"},
        {"Id":"228","Code":"TW","ThreeCode":"TWN","NumberCode":"158","Name":"Taiwan","ChineseName":"台湾"},
        {"Id":"229","Code":"TZ","ThreeCode":"TZA","NumberCode":"834","Name":"Tanzania, United Republic of","ChineseName":"坦桑尼亚"},
        {"Id":"230","Code":"UA","ThreeCode":"UKR","NumberCode":"804","Name":"Ukraine","ChineseName":"乌克兰"},
        {"Id":"231","Code":"UG","ThreeCode":"UGA","NumberCode":"800","Name":"Uganda","ChineseName":"乌干达"},
        {"Id":"232","Code":"UM","ThreeCode":"UMI","NumberCode":"581","Name":"United States Minor Outlying Islands","ChineseName":"美国本土外小岛屿"},
        {"Id":"233","Code":"US","ThreeCode":"USA","NumberCode":"840","Name":"United States","ChineseName":"美国"},
        {"Id":"234","Code":"UY","ThreeCode":"URY","NumberCode":"858","Name":"Uruguay","ChineseName":"乌拉圭"},
        {"Id":"235","Code":"UZ","ThreeCode":"UZB","NumberCode":"860","Name":"Uzbekistan","ChineseName":"乌兹别克斯坦"},
        {"Id":"236","Code":"VA","ThreeCode":"VAT","NumberCode":"336","Name":"Holy See (Vatican City State)","ChineseName":"梵蒂冈"},
        {"Id":"237","Code":"VC","ThreeCode":"VCT","NumberCode":"670","Name":"Saint Vincent and the Grenadines","ChineseName":"圣文森特和格林纳丁斯"},
        {"Id":"238","Code":"VE","ThreeCode":"VEN","NumberCode":"862","Name":"Venezuela, Bolivarian Republic of","ChineseName":"委内瑞拉"},
        {"Id":"239","Code":"VG","ThreeCode":"VGB","NumberCode":"92","Name":"Virgin Islands, U.S.","ChineseName":"英属维尔京群岛"},
        {"Id":"240","Code":"VI","ThreeCode":"VIR","NumberCode":"850","Name":"United States Virgin Islands","ChineseName":"美属维尔京群岛"},
        {"Id":"241","Code":"VN","ThreeCode":"VNM","NumberCode":"704","Name":"Vietnam","ChineseName":"越南"},
        {"Id":"242","Code":"VU","ThreeCode":"VUT","NumberCode":"548","Name":"Vanuatu","ChineseName":"瓦努阿图"},
        {"Id":"243","Code":"WF","ThreeCode":"WLF","NumberCode":"876","Name":"Wallis and Futuna","ChineseName":"瓦利斯和富图纳"},
        {"Id":"244","Code":"WS","ThreeCode":"WSM","NumberCode":"882","Name":"Samoa","ChineseName":"萨摩亚"},
        {"Id":"245","Code":"YE","ThreeCode":"YEM","NumberCode":"887","Name":"Yemen","ChineseName":"也门"},
        {"Id":"246","Code":"YT","ThreeCode":"MYT","NumberCode":"175","Name":"Mayotte","ChineseName":"马约特"},
        {"Id":"247","Code":"ZA","ThreeCode":"ZAF","NumberCode":"710","Name":"South Africa","ChineseName":"南非"},
        {"Id":"248","Code":"ZM","ThreeCode":"ZMB","NumberCode":"894","Name":"Zambia","ChineseName":"赞比亚"},
        {"Id":"249","Code":"ZW","ThreeCode":"ZWE","NumberCode":"716","Name":"Zimbabwe","ChineseName":"津巴布韦"},
        {"Id":"250","Code":"AA","ThreeCode":"AA","NumberCode":"999","Name":"APO/FPO","ChineseName":"APO/FPO"},
        {"Id":"251","Code":"AN","ThreeCode":"AN","NumberCode":"999","Name":"Netherlands Antilles","ChineseName":"荷属安的列斯"},
        {"Id":"252","Code":"FX","ThreeCode":"FX","NumberCode":"NULL","Name":"FRANCE, METROPOLITAN","ChineseName":"法属美特罗波利坦"},
        {"Id":"253","Code":"IC","ThreeCode":"IC","NumberCode":"NULL","Name":"CANARY ISLANDS","ChineseName":"加那利群岛"},
        {"Id":"254","Code":"JU","ThreeCode":"JU","NumberCode":"NULL","Name":"YUGOSLAVIA","ChineseName":"南斯拉夫"},
        {"Id":"255","Code":"KV","ThreeCode":"KV","NumberCode":"NULL","Name":"KOSOVO","ChineseName":"科索沃"},
        {"Id":"256","Code":"TA","ThreeCode":"TA","NumberCode":"NULL","Name":"TRISTAN DA CUNBA","ChineseName":"特里斯坦"},
        {"Id":"257","Code":"XB","ThreeCode":"XB","NumberCode":"NULL","Name":"BONAIRE","ChineseName":"伯奈尔岛"},
        {"Id":"258","Code":"XC","ThreeCode":"XC","NumberCode":"NULL","Name":"CURACAO","ChineseName":"库拉索岛(荷兰)"},
        {"Id":"259","Code":"XD","ThreeCode":"XD","NumberCode":"NULL","Name":"ASCENSION","ChineseName":"阿森松"},
        {"Id":"260","Code":"XE","ThreeCode":"XE","NumberCode":"NULL","Name":"St.Eustatius","ChineseName":"圣尤斯塔提马斯岛"},
        {"Id":"261","Code":"XG","ThreeCode":"XG","NumberCode":"NULL","Name":"SPANISH TERRITORIES OF N.AFRICA","ChineseName":"北非西班牙属土"},
        {"Id":"262","Code":"XH","ThreeCode":"XH","NumberCode":"NULL","Name":"AZORES","ChineseName":"亚速尔群岛"},
        {"Id":"263","Code":"XI","ThreeCode":"XI","NumberCode":"NULL","Name":"MADEIRA","ChineseName":"马德拉岛"},
        {"Id":"264","Code":"XJ","ThreeCode":"XJ","NumberCode":"NULL","Name":"BALEARIC ISLANDS","ChineseName":"巴利阿里群岛"},
        {"Id":"265","Code":"XK","ThreeCode":"XK","NumberCode":"NULL","Name":"CAROLINE ISLANDS","ChineseName":"加罗林群岛"},
        {"Id":"266","Code":"XM","ThreeCode":"XM","NumberCode":"NULL","Name":"ST. MAARTEN","ChineseName":"圣马腾岛"},
        {"Id":"267","Code":"XN","ThreeCode":"XN","NumberCode":"NULL","Name":"NEVIS","ChineseName":"尼维斯岛"},
        {"Id":"268","Code":"XS","ThreeCode":"XS","NumberCode":"NULL","Name":"SOMALILAND","ChineseName":"索马里共和国"},
        {"Id":"269","Code":"XY","ThreeCode":"XY","NumberCode":"NULL","Name":"ST. BARTHELEMY","ChineseName":"圣巴特勒米岛"},
        {"Id":"270","Code":"ZR","ThreeCode":"ZR","NumberCode":"NULL","Name":"ZAIRE","ChineseName":"扎伊尔"},
        {"Id":"271","Code":"UK","ThreeCode":"UK","NumberCode":"NULL","Name":"United Kingdom","ChineseName":"英国"},
]

