export class EndPointsConfig {
  static EndPoints = {

    Login: '/api/v1/token',
    GetCurrentUserInfo: '/api/v1/session/GetCurrentUserInfo',

    PostCommonCountry: '/api/v1/Common/all-countries',
    Common_Get_All_Countries: '/api/v1/Common/all-countries',
    Common_Get_Provinces: '/api/v1/Common/provinces',
    Common_Get_Cities: '/api/v1/Common/cities',
    Common_Get_Regions: '/api/v1/Common/regions',

    GetCurrencyRateList: '/api/v1/CurrencyRate/GetCurrencyRateList',
    GetCurrencyRate: '/api/v1/CurrencyRate/GetCurrencyRate',

    GetCountryDeclarationAmount: '/api/v1/shipping/country-declaration-amount/list',
    PostCountryDeclarationAmount: '/api/v1/shipping/country-declaration-amount/save',

    Department_GetAllDepartmentList: '/api/v1/departmentService/List',
    Department_GetAllDepartmentOptionsList: '/api/v1/departmentService/OptionsList',
    Department_AddDepartment: '/api/v1/departmentService/Add',
    Department_UpdateDepartment: '/api/v1/departmentService/Update',
    Department_DeleteDepartment: '/api/v1/departmentService/:id/Deletel',
    Department_GetOneDepartment: '/api/v1/departmentService/:id',

    Role_GetRoleList: '/api/v1/roles/list',
    Role_GetAllRoleOptionsList: '/api/v1/roles/OptionsList',
    Role_AddRole: '/api/v1/roles/Add',
    Role_UpdateRole: '/api/v1/roles/Update',
    Role_DeleteRole: '/api/v1/roles/:id/Deletel',
    Role_GetOneRole: '/api/v1/roles/:id',
    Role_ResourceQuery: '/api/v1/roles/ResourceQuery',
    Role_DeleteRoleInfoById: '/api/v1/roles/DeleteRoleInfoById',
    Role_GetOperationByResource: '/api/v1/roles/GetOperationByResource',
    Role_SaveRoleAndResource: '/api/v1/roles/SaveRoleAndResource',
    Role_GetResourceTreeQuery: '/api/v1/roles/GetResourceTreeQuery',
    Permission_AllResourcesPermission: '/api/v1/permission-codes',


    Memeber_GetMemberList: '/api/v1/member/PageList',
    Memeber_GetAllRoleOptionsList: '/api/v1/roles/Add',
    Memeber_AddMember: '/api/v1/member/add',
    Memeber_UpdateMember: '/api/v1/member/Update',
    Memeber_GetOneMember: '/api/v1/member/:id',
    Memeber_SetMemberStatus: '/api/v1/member/SetMemberStatus',
    Memeber_SetMemberPassWord: '/api/v1/member/SetPassWord',

    Shop_Amazon_GetAccountList: '/api/v1/shops/amazon/pagelist',
    Shop_Amazon_CreateAccount: '/api/v1/shops/amazon/create',
    Shop_Amazon_GetChannelAccount: '/api/v1/shops/amazon/channelAccountList',

    Shop_AliExpress_GetAccountList: '/api/v1/shops/aliexpress/pagelist',
    Shop_AliExpress_GetLoginUrl: '/api/v1/shops/aliexpress/login-url',

    Shop_Wish_GetAccountList: '/api/v1/shops/wish/pagelist',
    Shop_Wish_GetLoginUrl: '/api/v1/shops/wish/login-url',

    Shop_Account_Disable: '/api/v1/shops/:id/disable',
    Shop_Account_Enable: '/api/v1/shops/:id/enable',
    Shop_All_Accounts_List: '/api/v1/shops/all-accounts',
    Shop_All_Carrier_Codes: '/api/v1/shops/all-carrier-codes',
    Shop_GetEmailAccountByUserId: '/api/v1/Email/GetEmailAccountByUserId',
    Shop_SetCurrentAccount: '/api/v1/Email/SetCurrentAccount',


    ShippingProvider_Authroized_Lite_List: '/api/v1/sp/all-authroized',
    ShippingProvider_Lite_List: '/api/v1/sp/all',
    ShippingProvider_Lite_NeedAuth_List: '/api/v1/sp/need-auth-all',
    ShippingProvider_AuthMetaData: '/api/v1/sp/:id/auth-metadatas',
    ShippingProvider_AuthData: '/api/v1/sp/:id/auth-data',
    ShippingProvider_DoAuthroize: '/api/v1/sp/do-authroize',
    ShippingProvider_DoCreateAuthroizeRequest: '/api/v1/sp/CreateAuthorizeRequest',

    Warehouse_All_Option_List: '/api/v1/Warehouse/all-options',
    Warehouse_Page_List: '/api/v1/Warehouse/List',
    Warehouse_Package_Reallocate_Shipping: '/api/v1/package/reallocate-shipping',
    Warehouse_Set_Warehouse_Status: '/api/v1/Warehouse/SetWarehouseStatus',
    Warehouse_Get_WarehoseDetail: '/api/v1/Warehouse/:warehouseId',
    Warehouse_Add_Warehouse: '/api/v1/Warehouse/add',
    Warehouse_Edit_Warehouse: '/api/v1/Warehouse/Update',
    Warehouse_Get_Warehouse_Batch_Setting: '/api/v1/Warehouse/BatchManagement/:warehouseId',
    Warehouse_Save_Warehouse_Batch_Setting: '/api/v1/Warehouse/BatchManagement/set',
    Warehouse_Get_LocationPageList: '/api/v1/Warehouse/LocationList',
    Warehouse_Add_Location_Code: '/api/v1/Warehouse/AddLocationCode',
    Warehouse_Delete_Location_Code: '/api/v1/Warehouse/Loction/:locationId/Delete',
    Warehouse_Lock_Location_Code: '/api/v1/Warehouse/Loction/:locationId/lock',
    Warehouse_Unlock_Location_Code: '/api/v1/Warehouse/Loction/:locationId/unlock',
    Warehouse_Area_List: '/api/v1/Warehouse/:warehouseId/Area/List',
    Warehouse_Area_Lock: '/api/v1/Warehouse/:warehouseId/Area/:areaId/lock',
    Warehouse_Area_Unlock: '/api/v1/Warehouse/:warehouseId/Area/:areaId/unlock',

    Warehouse_PickTask_List: '/api/v1/Warehouse/GetPickTaskQuery',
    Warehouse_UpdatePickTask: '/api/v1/Warehouse/UpdatePickTask',
    Warehouse_PickScan_List: '/api/v1/Warehouse/GetPackageScanQuery',
    Warehouse_Calculate_Package: '/api/v1/Warehouse/CalculatePackageForQuery',
    Warehouse_GetAllUsers: '/api/v1/Warehouse/GetAllUsers',
    Warehouse_Picking_SetDanPinPackageFailed: '/api/v1/pickings/set-dan-pin-duo-package-picking-failed',
    Warehouse_Picking_Second_PickingInfo: '/api/v1/pickings/picking-second-info',
    Warehouse_Picking_Second_Picking_Sku: '/api/v1/pickings/do-sencond-picking/:pickingId',
    Warehouse_Picking_Second_Picking_Set_Package_PickingFailed: '/api/v1/pickings/set-package-picking-failed',
    Warehouse_Picking_Second_Pre_Allocate_UnScanPackages: '/api/v1/pickings/pre-allocate-unscan-package',
    Warehouse_Picking_AssignedPickTaskToUserById: '/api/v1/Warehouse/AssignedPickTaskToUserById',
    Warehouse_Picking_PickTaskForSkuById: '/api/v1/Warehouse/PickTaskForSkuById',
    Warehouse_Picking_PickTaskForSkuDetailById: '/api/v1/Warehouse/PickPackageDetailForSkuDetailByPackageId',
    Warehouse_Picking_PickPackageDetailById: '/api/v1/Warehouse/PickPackageDetailById',
    Warehouse_Picking_PickUpPackageFailed: '/api/v1/package/PickUpPackageFailed',
    Warehouse_Picking_GetPackageTotalQuantity: '/api/v1/Warehouse/GetPackageTotalQuantity',
    ShippingService_Page_List: '/api/v1/shipping/shipping-method/list',
    ShippingService_Select_Ss: '/api/v1/shipping/shipping-method/:ssId/select',
    ShippingService_UnSelect_Ss: '/api/v1/shipping/shipping-method/:ssId/unselect',
    ShippingService_Delete_Custom_Service: '/api/v1/shipping/shipping-method/:ssId/delete-custom-ss',

    ShippingService_Warehouse_All_Active_Service: '/api/v1/shipping/shipping-method/:warehouseId/all-options',
    ShippingService_Warehouse_Pocket: '/api/v1/shipping/shipping-method/:warehouseId/all-options-pocket',

    ShippingService_GetWarehouseShippingServiceForPackage: '/api/v1/shipping/shipping-method/GetWarehouseShippingServiceForPackage',
    ShippingService_GetSpServiceForPackage: '/api/v1/shipping/shipping-method/GetSpServiceForPackage',
    ShippingService_ShippingFeeRuleFinanceListQuery: '/api/v1/feerulefinance/ShippingFeeRuleFinanceListQuery',

    ShippingService_Detail: '/api/v1/shipping/shipping-method/:warehouseId/detail/:ssId',
    ShippingService_Detail_SaveSetting: '/api/v1/shipping/shipping-method/:warehouseId/detail/:ssId/save',
    ShippingService_Create: '/api/v1/shipping/shipping-method/create-custom-ss',

    ShippingService_Method_ImportFakeTrackingNumbers: '/api/v1/shipping/shipping-method/import/fake-tracking-numbers',
    ShippingService_Method_ListFakeTrackingNumbers: '/api/v1/shipping/shipping-method/list/fake-tracking-numbers',
    ShippingService_Method_DeleteFakeTrackingNumber: '/api/v1/shipping/shipping-method/delete/fake-tracking-number',


    ShippingService_Fee_Rule_Page_List: '/api/v1/shipping/shipping-ShippingFeeRule/:ssId/shipping-fee-rule-list',
    ShippingService_Fee_Rule_Detail: '/api/v1/shipping/shipping-ShippingFeeRule/:ssId/detail/:ruleId',
    ShippingService_Fee_Rule_Save: '/api/v1/shipping/shipping-ShippingFeeRule/save',
    ShippingService_Fee_Rule_Delete: '/api/v1/shipping/shipping-ShippingFeeRule/:ssId/:ruleId/delete',


    Announcement_Page_Add: '/api/v1/announcement/add',
    Announcement_Page_List: '/api/v1/announcement/PageList',
    Announcement_Page_Delete: '/api/v1/announcement/:id/delete',
    Announcement_Page_Update: '/api/v1/announcement/Update',
    Announcement_Page_Detail: '/api/v1/announcement/detail/:id',
    Announcement_Page_SetStatus: '/api/v1/announcement/SetStatus',


    Sku_Save: '/api/v1/sku/save',
    Sku_Delete: '/api/v1/sku/:skuId/delete',
    Sku_Update: '/api/v1/sku/Update',
    Sku_Detail: '/api/v1/sku/detail/:skuId',
    Sku_PageList: '/api/v1/sku/SkuList',
    Sku_Set_Status: '/api/v1/sku/SetStatus',
    Sku_GetSkuListBySearch: '/api/v1/sku/GetSkuListBySearch',
    Sku_DisableSku: '/api/v1/sku/disable',
    Sku_ActivateSku: '/api/v1/sku/activate',
    Sku_SkuSearch: '/api/v1/sku/skusearch',

    ChannelSku_PageList: '/api/v1/channelSku/channelSkuList',
    getSkuOrVirtualSkuList: '/api/v1/channelSku/skuOrVirtualSkuList',
    channelSkuSave: '/api/v1/channelSku/save',
    Channel_Sku_Delete: '/api/v1/channelSku/:skuId/DeletelChannelSku',
    Channel_Sku_Detail: '/api/v1/channelSku/:skuId/GetChannelSkuById',

    OrderRules_RulesList: '/api/v1/OrderRule/GetOrderRules',
    OrderRulesAdd: '/api/v1/OrderRule/AddOrderRules',
    OrderRulesItemRule_List: '/api/v1/OrderRule/GetAuditOrderRuleItemByRuleId',
    OrderRulesSetStatus: '/api/v1/OrderRule/SetOrderRulesStatus',
    OrderRulesDel: '/api/v1/OrderRule/DeleteOrderRule',
    OrderChannelShipping: '/api/v1/OrderRule/GetChannelShipppingMethods',
    OrderUpdateRulePriority: '/api/v1/OrderRule/UpdateRuleOrderPriority',
    WarehouseUpdateRulePriority: '/api/v1/OrderRule/UpdateRuleWarehousePriority',
    ShipUpdateRulePriority: '/api/v1/OrderRule/UpdateRuleShipPriority',
    OrderRulesChangeOrderProtityByRuleId: '/api/v1/OrderRule/ChangeOrderProtityByRuleId',

    Virtual_Sku_Sku_Save: '/api/v1/virtualsku/save',
    Virtual_Sku_Delete: '/api/v1/virtualsku/:skuId/DeletelVirtualSku',
    Virtual_Sku_Update: '/api/v1/virtualsku/save',
    Virtual_Sku_Detail: '/api/v1/virtualsku/:skuId/GetVirtualSkuById',
    Virtual_Sku_PageList: '/api/v1/virtualsku/List',

    Orders_All_List: '/api/v1/Orders/all-orders',
    Orders_All_GetOrderPostBackList: '/api/v1/Orders/getOrderPostBackList',
    Orders_All_GetOrderAdvancePostBackList: '/api/v1/Orders/GetOrderAdvancePostBackList',
    Orders_All_GetOrderPostBackInfo: '/api/v1/Orders/getOrderPostBackInfo',
    Orders_All_OrderNoPostBack: '/api/v1/Orders/OrderNoPostBack',
    Orders_All_OrderAdvancePostBack: '/api/v1/Orders/OrderAdvancePostBack',
    Orders_Order_Detail: '/api/v1/order-detail/:orderId',
    Orders_Order_GetOrderEmailDetail: '/api/v1/Orders/GetOrderEmailDetail',
    Orders_Order_Detail_Save_Address: '/api/v1/order-detail/:orderId/save-shipping-address',
    Orders_Order_Detail_Save_OrderLines: '/api/v1/order-detail/:orderId/save-orderlines',
    Orders_Order_Detail_Save_Declaration: '/api/v1/order-detail/:orderId/save-declaration',
    Orders_Void_Order: '/api/v1/Orders/:orderId/void',
    Orders_BackComesBack_Order: '/api/v1/order-detail/:orderId/orderBackComesBack',
    Orders_Reset_Order: '/api/v1/Orders/:orderId/reset',
    Orders_Active_Order: '/api/v1/Orders/:orderId/active',
    Orders_Order_Detail_Add_Note: '/api/v1/order-detail/:orderId/add-order-note',
    Orders_Order_Detail_Save_AllocateInfo: '/api/v1/order-detail/:orderId/save-alloate-info',
    Orders_Lock_Order: '/api/v1/Orders/:orderId/lock',
    Orders_Unlock_Order: '/api/v1/Orders/:orderId/unlock',
    Orders_OrderPostBack: '/api/v1/Orders/OrderPostBack',
    Orders_Order_Detail_Fetch_TrackingNumber: '/api/v1/order-detail/:orderId/get-trackingNumber',
    Orders_Order_CreateManualOrders: '/api/v1/ManualOrders/add',
    Orders_Order_OrderDefuseQuery: '/api/v1/Orders/OrderDefuseQuery',
    Orders_Order_OrderDefuse: '/api/v1/Orders/OrderDefuse',
    Orders_Pending_Allocation_Order_List: '/api/v1/pending-allocation-orders/pagelist',
    Orders_Pending_Allocation_Order_GeneratePackages: '/api/v1/pending-allocation-orders/GeneratePackages',
    Orders_OrderCombineQuery: '/api/v1/Orders/OrderCombineQuery',
    Orders_Order_OrderCombine: '/api/v1/Orders/OrderCombine',
    Orders_Order_GetOrderLogActionQuery: '/api/v1/Orders/GetOrderLogActionQuery',
    Orders_Order_ChangeOrderPrority: '/api/v1/Orders/ChangeOrderPrority',
    WarehouseRules_RuleList: '/api/v1/OrderRule/GetWarehouseRules',
    WarehouseRulesAdd: '/api/v1/OrderRule/AddWarehousesRules',

    LogisticsRules_RuleList: '/api/v1/OrderRule/GetLogisticsRules',
    Logistics_WareHouseIdByRuleType: '/api/v1/OrderRule/GetWareHouseIdByRuleType',
    Logicstics_GetWarehouseShippingQuery: '/api/v1/OrderRule/GetWarehouseShippingQuery',
    LogicsticsRulesAdd: '/api/v1/OrderRule/AddLogicsticsRules',
    OrderRules_Platform: '/api/v1/OrderRule/GetAccountPlatform',
    OrderRules_Accounts: '/api/v1/OrderRule/GetChannelAccounts',
    OrderRules_GetChannelAccountsByCountry: '/api/v1/OrderRule/GetChannelAccountsByCountry',

    Package_Search_PageList: '/api/v1/package/PackageList',
    Package_Search_NotShipmentPackageList: '/api/v1/package/NotShipmentPackageList',
    Package_Search_PackagePickingFailList: '/api/v1/package/PackagePickingFailList',
    Package_Search_GetPackagePickingFailInfoById: '/api/v1/package/GetPackagePickingFailInfoById',
    Package_Search_CreatNewExceptionInformation: '/api/v1/package/CreatNewExceptionInformation',
    Package_Search_PackageDefuseQuery: '/api/v1/package/PackageDefuseQuery',
    Package_Search_PackageDefuse: '/api/v1/package/PackageDefuse',
    Package_Detail: '/api/v1/package/GetPackageInfoById',



    Finance_Package_SpFee_PageList: '/api/v1/feerulefinance/PageList',
    Finance_Package_SpFee_GetPackageInfoById: '/api/v1/feerulefinance/GetPackageInfoById',
    Finance_Package_SpFee_SaveSpFeeChecking: '/api/v1/feerulefinance/SaveSpFeeChecking',

    PackagePocket_PackagePocketQuery:'/api/v1/packagepocket/PackagePocketQuery',
    PackagePocket_GetPackageByPocketNumber:'/api/v1/packagepocket/GetPackageByPocketNumber',
    PackagePocket_SendPackagePocket:'/api/v1/packagepocket/SendPackagePocket',


    GetWarehouseStoreage: '/api/v1/Warehouse/GetWarehouseStoreageQuery',
    GetStockOverFlowQuery: '/api/v1/Warehouse/GetStockOverFlowQuery',
    Package_Fetch_TrackingNumber: '/api/v1/package/:packageId/fetchTrackingNumber',
    GetReceiveRecordQuery: '/api/v1/Warehouse/GetReceiveRecordQuery',
    AddReceiveRecord: '/api/v1/Warehouse/AddReceiveRecord',
    Package_Get_Shipment_Info: '/api/v1/package-shipment/scan-ship/get-shipment-info',
    Package_Do_Scan_Ship: '/api/v1/package-shipment/do-scan-ship',
    Package_GetPickPrintQuery: '/api/v1/package/GetPickPrintQuery',
    Package_CancelPackageByPackageId: '/api/v1/package/CancelPackageByPackageId',
    OrderException_ConfirmUpdateSiteTrackingNumber: '/api/v1/OrderException/confirmUpdateSiteTrackingNumber',
    OrderException_Search_PageList: '/api/v1/OrderException/GetAllOrderLitException',
    //  OrderException_Search_AllOrderId: '/api/v1/OrderException/OnCheckAllPageChange',
    OrderException_Order_Approved: '/api/v1/OrderException/approved',
    OrderException_Order_LowProfit_Approved: '/api/v1/OrderException/lowprofit-approved',
    OrderException_Order_ResetOrder: '/api/v1/OrderException/resetOrder',
    OrderException_Order_ContinueShipmentsOrder: '/api/v1/OrderException/continueShipmentsOrder',
    OrderException_Order_ContinueShipmentsOrderById: '/api/v1/OrderException/continueShipmentsOrderById',
    OrderException_Order_VoidedOrder: '/api/v1/OrderException/voidedOrder',
    OrderException_Order_LockOrder: '/api/v1/OrderException/lockOrder',
    OrderException_Order_ChangeShippingService: '/api/v1/OrderException/changeShippingService',
    OrderException_Order_needTrcukNumber: '/api/v1/OrderException/needTrcukNumber',
    OrderException_Order_getAllOrderExceptionCount: '/api/v1/OrderException/GetAllOrderExceptionCount',

    OrderException_Order_GetCompleteSaleOrderInfoById: '/api/v1/OrderException/get-complete-sale-info',
    OrderException_Order_DoEditCompleteSale: '/api/v1/OrderException/do-edit-complete-sale',
    OrderException_DoOpeartionForNeedTrackNum: '/api/v1/OrderException/DoOpeartionForNeedTrackNum',


    OrderException_Search_NeedMerge_PageList: '/api/v1/OrderException/need-merge-order-list',
    OrderException_Ignore_Order_Merge: '/api/v1/OrderException/ignore-merge',

    OrderException_Order_manualEntryTrackingNumberr: '/api/v1/package/manualEntryTrackingNumber',
    OrderException_Order_NoComesBack: '/api/v1/OrderException/noComesBack',
    Warehouse_Picking_Manual_AfreshBackComesBack: '/api/v1/OrderException/afreshBackComesBack',
    Warehouse_PendingGeneratePickingPackageCount: '/api/v1/pickings/pending-generate-package-count',
    Warehouse_Picking_Manual_GeneratePicking: '/api/v1/pickings/manual-generate',
    Warehouse_CalePackageBySearchCode: '/api/v1/Warehouse/CalePackageBySearchCode',

    Warehouse_CombineUnpackRecorderQuery: '/api/v1/unpackage/CombineUnpackRecorderQuery',
    Warehouse_CombineUnpackInStore: '/api/v1/unpackage/CombineUnpackInStore',

    Warehouse_SearchPackageProductQuery: '/api/v1/Warehouse/SearchPackageProductQuery',
    Warehouse_SearchPackagePageQuery: '/api/v1/Warehouse/SearchPackagePageQuery',
    Warehouse_UpdatePackageItemStatusQuery: '/api/v1/Warehouse/UpdatePackageItemStatusQuery',
    Warehouse_UpdatePackageStatusQuery: '/api/v1/Warehouse/UpdatePackageStatusQuery',
    Supplier_List_Page: '/api/v1/suppliers/pagelist',
    Purchase_PlanQuery: '/api/v1/purchase-plan/PurchasePlanQuery',
    Purchase_PlanItemQuery: '/api/v1/purchase-plan/PurchasePlanItemQuery',
    Purchase_OrderPurchasePlanQuery: '/api/v1/purchase-plan/OrderPurchasePlanQuery',

    Purchase_Plan_Generate: '/api/v1/purchase-plan/generate/:warehouseId',
    Purchase_Plan_BatchParseSku: '/api/v1/purchase-plan/BatchParseSku',
    Purchase_Plan_CreatePurchasePlan: '/api/v1/purchase-plan/CreatePurchasePlan',
    Purchase_Plan_GeneratePurchaseOrder: '/api/v1/purchase-plan/generate-purchase-order',
    Purchase_UpdatePurchasePlanCount: '/api/v1/purchase-plan/UpdatePurchasePlanCount',
    Purchase_ActivaPurchasePlan: '/api/v1/purchase-plan/ActivaPurchasePlan',
    PurchaseUrl_AddPurchaseUrl: '/api/v1/purchase-url/AddPurchaseUrl',
    PurchaseUrl_DeletePurchaseUrl: '/api/v1/purchase-url/DeletePurchaseUrl',
    PurchaseUrl_PurchaseUrlQuery: '/api/v1/purchase-url/PurchaseUrlQuery',
    PurchaseUrl_PurchaseUrlGroupQuery: '/api/v1/purchase-url/PurchaseUrlGroupQuery',
    PurchaseUrl_SetDefaultUrl: '/api/v1/purchase-url/SetDefaultUrl',
    PurchaseUrl_SetMailPurchaseUrl: '/api/v1/purchase-url/SetMailPurchaseUrl',
    Supplier_Add: '/api/v1/suppliers/add',
    Supplier_Enable: '/api/v1/suppliers/enable',
    Supplier_Disable: '/api/v1/suppliers/disable',
    Supplier_List: '/api/v1/suppliers/GetSupplierList',

    GetUserInfo: '/api/v1/user/detail',
    User_EditInfo: '/api/v1/user/edit',
    User_EditUserImage: '/api/v1/user/editUserImage',
    User_ChangePassWrod: '/api/v1/user/changePassWrod',
    BlacklistUser_GetBlacklistUserList: '/api/v1/blacklistUser/getBlacklistUserList',
    BlacklistUser_GetBlacklistUserInfoById: '/api/v1/blacklistUser/GetBlacklistUserInfoById',
    BlacklistUser_DeteleBlacklistUserById: '/api/v1/blacklistUser/DeteleBlacklistUserById',
    BlacklistUser_CreateBlacklistUser: '/api/v1/blacklistUser/CreateBlacklistUser',

    Order_Detail_OrderReissue: '/api/v1/order-detail/orderReissue',

    Ali1688Accounts_Page_List: '/api/v1/ali1688-accounts/list',
    Ali1688Accounts_Account_Detail: '/api/v1/ali1688-accounts/detail/:accountId',
    Ali1688Accounts_Auth_Get_Login_Url: '/api/v1/ali1688-accounts/auth-login-url',
    Ali1688Accounts_ReAuth_Get_Login_Url: '/api/v1/ali1688-accounts/auth-login-url/:accountId',
    Ali1688Accounts_Enable: '/api/v1/ali1688-accounts/:accountId/enable',
    Ali1688Accounts_Disable: '/api/v1/ali1688-accounts/:accountId/disable',
    Ali1688Accounts_Edit_Address: '/api/v1/ali1688-accounts/:accountId/edit-address',
    Ali1688Accounts_List: '/api/v1/ali1688-accounts/getlist',
    Ali1688Accounts_setloginpassword: '/api/v1/ali1688-accounts/:accountId/set-login-password',

    PurchaseSkuOrder_Page_List: '/api/v1/PurchaseSkuOrder/GetAllPurchaseSkuOrder',
    PurchaseSkuOrder_Set_ActualNumber: '/api/v1/PurchaseSkuOrder/SetActualNumber',
    PurchaseSkuOrder_Set_OverLookOrder: '/api/v1/PurchaseSkuOrder/OverLookOrder',
    PurchaseSkuOrder_Create_1688Order: '/api/v1/PurchaseSkuOrder/Create1688Order',
    PurchaseSkuOrder_Get_PurchaseHistoryList: '/api/v1/PurchaseSkuOrder/PurchaseHistoryList',
    PurchaseSkuOrder_Get_PurchaseSkuOrderDetail: '/api/v1/PurchaseSkuOrder/PurchaseSkuOrderDetail',
    PurchaseSkuOrder_Get_WarehouseForPurchaseSkuOrder: '/api/v1/PurchaseSkuOrder/GetWarehouseForPurchaseSkuOrder',
    PurchaseSkuOrder_Get_ChangeDisCountPrice: '/api/v1/purchase-platformorder/ChangeDisCountPrice',
    PurchaseSkuOrder_PurchaseSkuOtherOrderList: '/api/v1/PurchaseSkuOrder/PurchaseSkuOtherOrderList',
    PurchaseSkuOrder_PurchaseSkuSave: '/api/v1/PurchaseSkuOrder/PurchaseSkuSave',
    PurchaseSkuOrder_GetOtherPendPurchaseOrder: '/api/v1/PurchaseSkuOrder/GetOtherPendPurchaseOrder',
    PurchaseSkuOrder_CreateOtherOrder: '/api/v1/PurchaseSkuOrder/CreateOtherOrder',
    PurchaseSkuOrder_MergePurchaseForSameOtherNumber: '/api/v1/PurchaseSkuOrder/MergePurchaseForSameOtherNumber',

    PurchasePlatform_Order_PlatformOrderQuery: '/api/v1/purchase-platformorder/PlatformOrderQuery',
    PurchasePlatform_Order_PlatformOrderSearchQuery: '/api/v1/purchase-platformorder/PlatformOrderSearchQuery',
    PurchasePlatform_Order_GetUserListQuery: '/api/v1/purchase-platformorder/GetUserListQuery',
    PurchasePlatform_Order_GetPlatformOrderDetailQuery: '/api/v1/purchase-platformorder/GetPlatformOrderDetailQuery',
    PurchasePlatform_Order_GetPlatformOrderSearchQuery: '/api/v1/purchase-platformorder/GetPlatformOrderSearchQuery',
    PurchasePlatformOrder_OtherPlatformOrderQuery: '/api/v1/purchase-platformorder/OtherPlatformOrderQuery',
    PurchasePlatformOrder_PlatformOtherOrderSearchQuery: '/api/v1/purchase-platformorder/PlatformOtherOrderSearchQuery',
    PurchasePlatformOrder_CancelOtherOrder: '/api/v1/purchase-platformorder/CancelOtherOrder',


    System_Config_Get_Purchase_Config: '/api/v1/system-config/get-purchase-config',
    System_Config_Save_Purchase_Config: '/api/v1/system-config/SavePurchaseConfig',
    PurchasePlatform_Order_AddPlatformLogistics: '/api/v1/purchase-platformorder/AddPlatformLogistics',
    PurchasePlatform_Order_UpdatePlatformLogistics: '/api/v1/purchase-platformorder/UpdatePlatformLogistics',
    PurchasePlatform_Order_Sync: '/api/v1/purchase-platformorder/SyncOrder',
    PurchasePlatform_Order_BatchSync: '/api/v1/purchase-platformorder/BatchSyncOrders',
    PurchasePlatform_Order_BatchAllSync: '/api/v1/purchase-platformorder/BatchAllSyncOrders',
    PurchasePlatform_Order_Refuse: '/api/v1/purchase-platformorder/RefuseOrder',
    PurchasePlatform_ConfirmPayForOrder: '/api/v1/purchase-platformorder/ConfirmPayForOrder',
    PurchasePlatform_ConfirmPriceForOrder: '/api/v1/purchase-platformorder/ConfirmPriceForOrder',
    PurchasePlatformOrder_ConfirmPayForOtherOrder: '/api/v1/purchase-platformorder/ConfirmPayForOtherOrder',

    PurchasePlatform_DeletePlatformLogistics: '/api/v1/purchase-platformorder/DeletePlatformLogistics',
    PurchasePlatform_PlatformOrderProcessingComplete: '/api/v1/purchase-platformorder/PlatformOrderProcessingComplete',
    PurchasePlatform_UpdateBuyCount: '/api/v1/purchase-platformorder/UpadateBuyCount',
    PurchasePlatform_GetPlatformOrderSkuArrivalGoodsDetailQuery: '/api/v1/purchase-platformorder/GetPlatformOrderSkuArrivalGoodsDetailQuery',
    PurchasePlatform_Order_ManualFinished: '/api/v1/purchase-platformorder/ManualFinishPurchaseOrder',
    WarehouseUnpack_SearchOrderInfo: '/api/v1/unpackage/GetAliOrderInfo',
    WarehouseUnpack_PurchasePlatformOrderNote: '/api/v1/unpackage/AddNote',
    WarehouseUnpack_GetPurchasePlatformOrderNotes: '/api/v1/unpackage/GetPurchasePlatformOrderNotes',
    WarehouseUnpack_DoInstock: '/api/v1/unpackage/instock',

    Warehouse_Package_Return_Records_PageList: '/api/v1/package-return/page-list-records',
    Warehouse_Package_Return_Records_Add: '/api/v1/package-return/add-return-record',
    Warehouse_Package_Return_Records_GetNote: '/api/v1/package-return/get-return-record-note',
    Warehouse_Package_Return_Records_SetNote: '/api/v1/package-return/set-return-record-note',
    Warehouse_Package_Return_Records_MarkShipped: '/api/v1/package-return/mark-return-record-package-shipped',

    OrderCompleteSaleRule_List: '/api/v1/OrderCompleteSaleRule/list',
    OrderCompleteSaleRule_Save: '/api/v1/OrderCompleteSaleRule/save',
    OrderCompleteSaleRule_Delete: '/api/v1/OrderCompleteSaleRule/delete',
    OrderCompleteSaleRule_Disable: '/api/v1/OrderCompleteSaleRule/disable',
    OrderCompleteSaleRule_Enable: '/api/v1/OrderCompleteSaleRule/enable',
    OrderCompleteSaleRule_Detail: '/api/v1/OrderCompleteSaleRule/detail',

    Email_GetEmailQuery: '/api/v1/Email/GetEmailQuery',
    Email_GetEmailDetailById: '/api/v1/Email/GetEmailDetailById',
    EmailTemplate_GetEmailTemplateQuery: '/api/v1/Email/GetEmailTemplateQuery',
    EmailTemplate_GetEmailTemplateById: '/api/v1/Email/GetEmailTemplateById',
    EmailTemplate_EmailTemplateOperation: '/api/v1/Email/EmailTemplateOperation',
    EmailTemplate_GetTemplateForEnable: '/api/v1/Email/GetTemplateForEnable',
    EmailTemplate_GetTemplateByAccount: '/api/v1/Email/GetTemplateByAccount',
    EmailTemplate_EmailTemplateDeleteById: '/api/v1/Email/EmailTemplateDeleteById',
    EmailTemplate_EmailTemplateEnableById: '/api/v1/Email/EmailTemplateEnableById',
    Email_SendEmail: '/api/v1/Email/SendEmail',
    Email_SetEmailReadByIds: '/api/v1/Email/SetEmailReadByIds',
    Email_SetEmailStarByIds: '/api/v1/Email/SetEmailStarByIds',
    Email_SetEmailExceptionByIds: '/api/v1/Email/SetEmailExceptionByIds',
    Email_SetEmailNoSeenByIds: '/api/v1/Email/SetEmailNoSeenByIds',
    Email_NoReplySumQuery: '/api/v1/Email/NoReplySumQuery',
    Email_CurrentReplySumQuery: '/api/v1/Email/CurrentReplySumQuery',
    Email_SaveNoteCate: '/api/v1/Email/SaveNoteCate',
    Email_SetOnlyEmailSeen: '/api/v1/Email/SetOnlyEmailSeen',
    Email_GetEmailTemplateAdvQuery: '/api/v1/Email/GetEmailTemplateAdvQuery',
    Email_SendEmailByOrder: '/api/v1/Email/SendEmailByOrder',

    Shipping_Track_PageList: '/api/v1/trackingOrder/trackingOrderList',
    Shipping_TrackEvents_List: '/api/v1/trackingOrder/getOrderTrackingEvents',
    Shipping_GetTrackingOrderCountByStatus: '/api/v1/trackingOrder/GetTrackingOrderCountByStatus',
    Packages_Void_Package: '/api/v1/package/:packageId/void',
    Packages_Edid_tPackageShipWeight: '/api/v1/package/:packageId/editPackageShipWeight',
    Packages_Create_CustomTruckingNumbers: '/api/v1/package/CreateCustom-tracking-number',
    Packages_Get_CustomTruckingNumbers: '/api/v1/package/:ssId/get-tracking-number',
    Inventory_Unlock: '/api/v1/Warehouse/Inventory/unlock',
    Inventory_Lock: '/api/v1/Warehouse/Inventory/lock',
    Warehouse_PickingFailRecord_SkuList: '/api/v1/picking-fail-records/sku-list',
    Warehouse_PickingFailRecord_CreateCheckingStockTask: '/api/v1/picking-fail-records/CreateCheckingStockTask',
    Warehouse_PickingFailRecord_CheckingStockTaskList: '/api/v1/picking-fail-records/CheckingStockTaskList',
    Warehouse_PickingFailRecord_TaskPrintData: '/api/v1/picking-fail-records/GetCheckingStockTaskPrintData',
    Warehouse_PickingFailRecord_GetPackagePickingFailDetail: '/api/v1/picking-fail-records/GetPackagePickingFailDetail',
    Warehouse_PickingFailRecord_ConfirmPurchase: '/api/v1/picking-fail-records/confirm-purchase',
    GetExchangeRateLossList: '/api/v1/CurrencyRate/exchangeRateLossList',
    SaveExchangeRateLoss: '/api/v1/CurrencyRate/save',
    ExchangeRateLoss_Delete: '/api/v1/CurrencyRate/DeletelExchangeRateLoss',
    EmployeeKPISave: '/api/v1/employeeKPI/SaveEmployeeKPI',
    GetEmployeeKPIList: '/api/v1/employeeKPI/GetEmployeeKPIList',
    DeleteEmployeeKPI: '/api/v1/employeeKPI/DeteleEmployeeKPIById',
    Employee_KPI_Detail: '/api/v1/employeeKPI/GetEmployeeKPIInfoById',

    Orderstatistics_QueryForChannel: '/api/v1/orderstatistics/QueryForChannel',
    Orderstatistics_QueryForOrderPriceStatistic: '/api/v1/orderstatistics/QueryForOrderPriceStatistic',
    OrderStatistics_GetOrderAccountMoneyStatisticQuery: '/api/v1/orderstatistics/GetOrderAccountMoneyStatisticQuery',
    PurchaseSkuOrder_GetPurchaseAccountsQuery: '/api/v1/PurchaseSkuOrder/GetPurchaseAccountsQuery',
    User_SetUserWithAccount: '/api/v1/user/SetUserWithAccount',
    User_GetUserByAccount: '/api/v1/user/GetUserByAccount',

    Brand_PageList: '/api/v1/brand/brandList',
    Brand_Save: '/api/v1/brand/save',
    Brand_Detail: '/api/v1/brand/detail/:brandId',
    Brand_Delete: '/api/v1/brand/:brandId/delete',

    Purchase_PurchaseAccount_Pagelist: '/api/v1/PurchaseAccounts/pagelist',
    Purchase_PurchaseAccount_AddAccount: '/api/v1/PurchaseAccounts/AddAccount',
    Purchase_PurchaseAccount_EditAccount: '/api/v1/PurchaseAccounts/EditAccount',
    Purchase_PurchaseAccount_SetAccountStatus: '/api/v1/PurchaseAccounts/SetAccountStatus',
    OrderStatistics_GetOrderLoseMoneyStatisticQuery: '/api/v1/orderstatistics/GetOrderLoseMoneyStatisticQuery',


    Package_ExceptionPackageList: '/api/v1/package/ExceptionPackageList',
    Package_SrceenList: '/api/v1/package/SrceenList',
    PurchaseAccount_GetAccountList: '/api/v1/PurchaseAccounts/GetAccountList',
    OrderCompleteSaleRule_GetMaxRulePriority: '/api/v1/OrderCompleteSaleRule/GetMaxRulePriority',
    OrderCompleteSaleRule_UpdateRulePriority: '/api/v1/OrderCompleteSaleRule/UpdateRulePriority',


    Inventory_ReserveInfo: '/api/v1/inventory/GetInventoryReserveInfo',
  }
}
