export  class tableService{
  detail=
  [
    {
      ebay:[
        {name:'所有',selected:1},
        {name:'WW',selected:0},
      ],
      amazon:{
        account:[
          {name:'所有',selected:1},
          {name:'df',selected:0},
          {name:'XDT',selected:0},
          {name:'xdztest',selected:0},
        ],
        distribution:[
          {name:'所有',selected:1},
          {name:'[FBA亚马逊配送]',selected:0},
          {name:'卖家自行配送',selected:0},
        ]
      },
      aliexpress:[
        {name:'所有',selected:1},
        {name:'WW',selected:0},
      ],
      wish:{
        account:[
          {name:'所有',selected:1},
          {name:'df',selected:0},
          {name:'XDT',selected:0},
          {name:'xdztest',selected:0},
        ],
        distribution:[
          {name:'所有',selected:1},
          {name:'WishExpress',selected:0},
          {name:'卖家自行配送',selected:0},
        ]
      },
      cd:{
        account:[
          {name:'所有',selected:1},
          {name:'df',selected:0},
          {name:'XDT',selected:0},
          {name:'xdztest',selected:0},
        ],
        distribution:[
          {name:'所有',selected:1},
          {name:'Cdiscount配送',selected:0},
          {name:'卖家自行配送',selected:0},
        ]
      }
    }
    ]
  constructor(){}
}

